version: '3.8'

services:
  annotation_service:
    image: "${DOCKER_HUB_REPO}"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /mnt/hdd_1:/mnt/hdd_1:rw
      - /dev/shm:/dev/shm
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${APP_PORT}:${APP_PORT}"
    # Web server command
    command: gunicorn app.main:socket_app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:${APP_PORT}
    restart: always
    depends_on:
      - mongodb
      - redis
    environment: &app_env
      MONGO_URI: ${MONGO_URI}
      APP_PORT: ${APP_PORT}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379/0
      REDIS_URL_BROKER: redis://redis:6379/1
      REDIS_EXPIRATION: 3600
      FASTAPI_APP: "true"
      MORK_DATA_DIR: ${MORK_DATA_DIR:-/mnt/hdd_1/biocypher-kg/output/hsa/metta_out_v6}
      FLY_MORK_DATA_DIR: ${FLY_MORK_DATA_DIR:-/mnt/hdd_1/biocypher-kg/output/dmel/metta}

  celery_worker:
    image: "${DOCKER_HUB_REPO}"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /mnt/hdd_1:/mnt/hdd_1:rw
      - /dev/shm:/dev/shm
      - /var/run/docker.sock:/var/run/docker.sock
    # Worker command
    command: celery -A app.workers.celery_app worker --loglevel=info
    restart: always
    depends_on:
      - annotation_service
      - redis
      - mongodb
    environment:
      <<: *app_env
      C_FORCE_ROOT: "1"

  mongodb:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "${MONGODB_DOCKER_PORT}:27017"
    restart: always

  redis:
    image: redis:latest
    ports:
      - "${REDIS_DOCKER_PORT:-6380}:6379"
    restart: always
    volumes:
      - redis_data:/data

  caddy:
    image: caddy:latest
    ports:
      - "${CADDY_PORT}:${CADDY_PORT_FORWARD}"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    command: caddy reverse-proxy --from http://0.0.0.0:${CADDY_PORT} --to http://annotation_service:${APP_PORT}
    restart: always
    depends_on:
      - annotation_service

volumes:
  mongo_data:
  redis_data:
  caddy_data:
  caddy_config: