services:
  annotation_service:
    image: "${DOCKER_HUB_REPO}"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "${APP_PORT}:${APP_PORT}"
    # Web server command
    command: gunicorn -k gthread -w 1 --threads 100 --bind 0.0.0.0:${APP_PORT} run:app
    restart: always
    depends_on:
      - mongodb
      - redis
    # We define the environment here and anchor it as &app_env
    # so we can simply reuse it in the celery_worker below.
    environment: &app_env
      - MONGO_URI=${MONGO_URI}
      - APP_PORT=${APP_PORT}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # Cache and Result Backend (DB 0)
      - REDIS_URL=redis://redis:6379/0
      # Celery Message Broker (DB 1)
      - REDIS_URL_BROKER=redis://redis:6379/1
      - REDIS_EXPIRATION=3600

  celery_worker:
    image: "${DOCKER_HUB_REPO}"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    # Worker command
    command: celery -A app.workers.celery_app worker --loglevel=info
    restart: always
    depends_on:
      - annotation_service
      - redis
      - mongodb
    # Reuse the exact same environment variables as the main app
    environment: *app_env

  mongodb:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
    ports:
      - "${MONGODB_DOCKER_PORT}:27017"
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    restart: always
    volumes:
      - redis_data:/data

  caddy:
    image: caddy:latest
    ports:
      - "${CADDY_PORT}:${CADDY_PORT_FORWARD}"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    command: caddy reverse-proxy --from http://0.0.0.0:${CADDY_PORT} --to http://annotation_service:${APP_PORT}
    restart: always
    depends_on:
      - annotation_service

volumes:
  mongo_data:
  redis_data:
  caddy_data:
  caddy_config:
