name: Bgee
website: https://www.bgee.org
relationships:
  gene expressed in anatomy:
    url: https://www.bgee.org/download/gene-expression-calls?id=
    input_label: gene_expressed_in_anatomy
    output_label: expressed_in
    description: holds between a gene and an anatomy ontology term in which it is expressed
    source: gene
    target: anatomy
    properties:
      p_value: float
      score: float
  gene expressed in developmental stage:
    url: https://www.bgee.org/download/gene-expression-calls?id=
    input_label: gene_expressed_in_developmental_stage
    output_label: expressed_in
    description: holds between a gene and a developmental stage in which it is expressed
    source: gene
    target: developmental_stage
    properties:
      p_value: float
      score: float
