name: MotifDiff
website: https://github.com/rezwanhosseini/MotifDiff
relationships:
  transcription factor to snp association:
    url: https://github.com/rezwanhosseini/MotifDiff
    input_label: tf_snp
    output_label: alters_binding
    description: >-
      holds between a SNP and a HOCOMOCO motif where the SNP causes a gain
      or loss of transcription factor binding affinity at that motif site
    source: snp
    target: motif
    properties:
      effect: str
      score: float
      motif_id: str
