name: STRING
website: https://string-db.org
relationships:
  post translational interaction:
    url: https://string-db.org/
    input_label: interacts_with
    output_label: interacts_with
    source: protein
    target: protein
    properties:
      score: float