name: CoXPresdb
description: Comprehensive gene coexpression database
website: https://coxpresdb.jp/
relationships:
  coexpressed with:
    url: https://coxpresdb.jp/
    description: Indicates that two genes are co-expressed, generally under the same conditions.
    input_label: coexpressed_with
    source: gene
    target: gene
    properties:
      score: float
