name: CoXPresdb
description: Comprehensive gene coexpression database
website: https://coxpresdb.jp/
relationships:
  coexpressed with:
    url: https://coxpresdb.jp/
    description: Indicates that two genes are co-expressed, generally under the same conditions.
    input_label: coexpressed_with
    source: gene
    target: gene
    properties:
      score: float

nodes:
  snp:
    url: https://asntech.org/dbsuper/download.php
    description: A cluster of enhancers that regulate cell identity genes
    input_label: snp
    properties:
      se_id: str
      chr: str
      start: int
      end: int
