name: STRING
website: https://string-db.org
relationships:
  post translational interaction:
    url: https://string-db.org/
    input_label: interacts_with
    source: protein
    target: protein
    properties:
      taxon_id: int
      score: float
  protein to protein coexpression association:
    url: https://string-db.org/
    input_label: protein_coexpressed_with
    output_label: coexpressed_with
    description: Indicates that two proteins are co-expressed, generally under the
      same conditions. Based on STRING coexpression data.
    source: protein
    target: protein
    properties:
      coexpression_score: float
