apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-staging
  namespace: annotation-staging
spec:
  selector:
    matchLabels:
      app: mongodb-staging
  serviceName: mongodb-staging
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb-staging
    spec:
      containers:
        - name: mongodb-staging
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: annotation-secrets
                  key: MONGO_USER
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: annotation-secrets
                  key: MONGO_PASS
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-staging
  namespace: annotation-staging
spec:
  selector:
    app: mongodb-staging
  ports:
    - port: 27017
      targetPort: 27017
