database:
  type: mork_cli
  human:
    data_dir: /mnt/hdd_1/biocypher-kg/output/hsa/metta_out_v6
    act_file: human_v6.act
    graph_info_path: ./Data/graph_info/hsa_v6.json

  # uncomment and fill in the following for fly data
  
  # fly:
  #   data_dir: /mnt/hdd_1/biocypher-kg/output/dmel/metta
  #   act_file: flybase.act
